name: deploy docker image on kubernetes cluster, using minikube in self-hosted runner

on:
  workflow_dispatch:

jobs: 
  main:
    runs-on: self-hosted
    
    steps:
      #- name: login to the system
      #  run: ssh ${{ secrets.IP }}
        
  #minikube:
  #  runs-on: self-hosted
  #  needs: main
 #   steps:
      - name: start minikube
        run: minikube start
  deploy:
    runs-on: self-hosted
    needs: main
    steps:
      - name: deploy and expose the application
        run: |
          kubectl create deployment laptop --image=bhavyabindela/laptop-store:v0.1 --port 1337
          sleep 30
          kubectl expose deploy/laptop --name laptop
          sleep 5
          kubectl port-forward svc/laptop 1337
          sleep 5
          curl http://localhost:1337
  cleanup:
    runs-on: self-hosted
    needs: deploy
    steps: 
      - name: cleanup the deployment
        run: kubectl delete deploy/laptop svc/laptop
          
