name: Node.js CI

on:
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm ci
        nohup npm start &
        sleep 5
        curl -v http://localhost:1337
        npm test
